name: paynext
services:
  frontend:
    container_name: paynext-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
